name: permit_pro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  image: ^4.3.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  intl: ^0.19.0
  url_launcher: ^6.3.1
  qr_flutter: ^4.0.0
  shared_preferences: ^2.3.3
  font_awesome_flutter: ^10.8.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/1024.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images.png
    - lib/assets/logo.png
    - assets/profile_placeholder.jpg
