name: permit_pro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  image: ^4.3.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images.png
    - lib/assets/logo.png
    - assets/profile_placeholder.jpg